# Generated by Django 5.0.6 on 2024-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projetderecherche_chef_de_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chercheur',
            name='email',
        ),
        migrations.AddField(
            model_name='chercheur',
            name='projets',
            field=models.ManyToManyField(blank=True, to='projects.projetderecherche'),
        ),
    ]
