# Generated by Django 5.0.6 on 2024-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_chercheur_email_chercheur_projets'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheur',
            name='specialite',
            field=models.CharField(default='specialite', max_length=100),
        ),
    ]
