# Generated by Django 5.0.6 on 2024-06-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_chercheur_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='auteur',
        ),
        migrations.AddField(
            model_name='publication',
            name='projet_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.projetderecherche'),
        ),
    ]
